---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}

unzip('activity.zip')
rawData <- read.csv('activity.csv')

```


## What is mean total number of steps taken per day?
```{r}
grouped = aggregate (steps ~ date, data = rawData, FUN=sum)
barplot(
    height    = grouped$steps, 
    names.arg = grouped$date,
    col       = rainbow(400), 
    las       = 2
)

grouped.mean <- mean(grouped$steps)
 

grouped.median <- median(grouped$steps)


```
mean is `r as.integer(grouped.mean)` and median is `r as.integer(grouped.median)`

## What is the average daily activity pattern?
```{r}
interval <- aggregate(steps ~ interval, data = rawData, FUN = mean)
plot(interval, type = "l")

maxRow <- which.max(interval$steps)
maxInt <- interval$interval[maxRow]

```
Interval contains the maximum number of steps is #`r maxInt`


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
